apiVersion: v1
kind: ConfigMap
metadata:
  name: tierra-config
data:
  ORACLE_USER: "TIERRA_EN_CALMA"
  ORACLE_PASS: "Tierracalma"
  ORACLE_CONN: "tierra-oracle:1521/XEPDB1"
  MQTT_BROKER: "tcp://tierra-mosquitto:1883"
  MQTT_USER: "admin"
  MQTT_PASS: "admin123"
  MQTT_TOPIC: "plantas/datos"
  PORT: "3000"
  HOST: "0.0.0.0"
  BASE_URL: "http://tierra-backend:3000"
