apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  selector:
    matchLabels:
      app: oracle
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
        - name: oracle-db
          image: gvenzl/oracle-xe:21-slim
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              value: Tierracalma
            - name: ORACLE_PDB
              value: XEPDB1
            - name: ORACLE_CHARACTERSET
              value: AL32UTF8
            - name: ORACLE_DISABLE_ASYNCH_IO
              value: "true"
